# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebScraping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('cantidad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tamaño en cc')),
                ('precio', models.FloatField(verbose_name='Precio en $')),
                ('imagen', models.CharField(blank=True, max_length=200, null=True, verbose_name='Imagen URL')),
                ('supermercado', models.CharField(blank=True, max_length=200, null=True, verbose_name='Super Mercado')),
            ],
            options={
                'verbose_name': 'My Web Scraping',
                'verbose_name_plural': 'My Web Scraping',
            },
        ),
        migrations.CreateModel(
            name='WebScrapingArtesanal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('cantidad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tamaño en cc')),
                ('precio', models.FloatField(verbose_name='Precio en $')),
                ('imagen', models.CharField(blank=True, max_length=200, null=True, verbose_name='Imagen URL ')),
                ('supermercado', models.CharField(blank=True, max_length=200, null=True, verbose_name='Super Mercado')),
            ],
            options={
                'verbose_name': 'My Web Scraping',
                'verbose_name_plural': 'My Web Scraping Artesanal',
            },
        ),
        migrations.CreateModel(
            name='WebScrapingPremium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('cantidad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tamaño en cc')),
                ('precio', models.FloatField(verbose_name='Precio en $')),
                ('imagen', models.CharField(blank=True, max_length=200, null=True, verbose_name='Imagen URL ')),
                ('supermercado', models.CharField(blank=True, max_length=200, null=True, verbose_name='Super Mercado')),
            ],
            options={
                'verbose_name': 'My Web Scraping',
                'verbose_name_plural': 'My Web Scraping Premium',
            },
        ),
    ]
