# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 01:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=200, verbose_name='RUT')),
                ('ciudad', models.CharField(max_length=200, verbose_name='Ciudad')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección del local')),
                ('fecha_de_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=200, verbose_name='Marca')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Tamaño en cc')),
                ('precio', models.PositiveIntegerField(default=0, verbose_name='Precio en $')),
                ('imagen_ref', models.FileField(upload_to='images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de usuario')),
            ],
            options={
                'verbose_name': 'Mi Producto',
                'verbose_name_plural': 'Mis Productos',
            },
        ),
        migrations.CreateModel(
            name='UploadImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('imagen', models.FileField(upload_to='producto/media')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Administrar Marca',
                'verbose_name_plural': 'Administrar Marcas',
            },
        ),
    ]
