# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artesanal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='producto_id',
        ),
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
